Add files for code review from my trials
supreeti/microverse-trial-review pull request #1
Opened 2022-12-13 14:57 UTC by supreeti

Code review form my trail projects

2022-12-13 15:05 UTC, supreeti reviewed
You can do it.

2022-12-13 15:05 UTC, supreeti commented on style.css
> +body {
Use proper workflow and add linters to your code. It helps in:-
Catching syntax errors is more efficient. 
There is no need to debug simple mistakes like typos - the linter does it for you.

2022-12-13 15:21 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - Good use of inline comments. ✔️
 - Good explanation of why to make changes. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] Your comment is good and explain why you ask for the changes. But your main comment does not look professional and does not inform the developer what the review is about like it needs to change something, it is approved, etc. Kindly make some changes in your main comment(you can get inspiration from this comment).

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
 - [OPTIONAL] You could use a couple of emojis and/or gifs in the review. They make the code review more human-friendly 👽🤖. Also you could format better the comment you request the change.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-13 16:39 UTC, supreeti reviewed
Changes required for linters-config

1. Use linter.yml file 
2. Use proper github workflow

2022-12-13 16:39 UTC, supreeti commented on style.css
> +body {
[Linters](https://github.com/microverseinc/linters-config/tree/master/html-css/.github/workflows)

2022-12-13 17:10 UTC, Favourezeugwa approved these changes
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @supreeti , 

I am Favour 👩🏽 , your reviewer for this PR

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉

![happy](https://user-images.githubusercontent.com/99246359/202491301-53f8c6a2-8ff4-4337-9b6b-9c75c8bdf345.gif)

## Highlights 💯 
- GitHub review feature used ✔️
- Inline comments used ✔️
- Suggestions were polite✔️
- Stated reasons WHY a requested change needs to be implemented ✔️ 

## Optional suggestions

[OPTIONAL] 👍🏽 
- As suggested by @leonardodiasb, i think it will be great to always include a GIF to your review summary and some emoji's to your suggestions inorder to make them sound more human friendly 🤗 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 10:14 UTC, supreeti commented
Thanks

2022-12-14 10:14 UTC, closed without merging